name: Build 16KB AAR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Inject Buildscript into Gradle
        run: |
          echo "buildscript { repositories { google(); mavenCentral(); jcenter() } dependencies { classpath 'com.android.tools.build:gradle:4.1.3' } }" > init.gradle
          echo "allprojects { repositories { google(); mavenCentral(); jcenter() } }" >> init.gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '6.7.1'

      # init.gradle dışarıdan bir kapsayıcı gibi gelip eksikleri sunar
      - name: Build AAR with NDK
        run: gradle assembleRelease --init-script init.gradle --stacktrace

      - name: Upload AAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-TiffBitmapFactory-16KB
          path: build/outputs/aar/*-release.aar
