name: Build 16KB AAR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build AAR with NDK
        run: |
          chmod +x ./gradlew
          ./gradlew :tiffbitmapfactory:assembleRelease --stacktrace

      - name: Upload AAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-TiffBitmapFactory-16KB
          path: tiffbitmapfactory/build/outputs/aar/tiffbitmapfactory-release.aar
