name: Build 16KB AAR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '6.7.1'

      # Alt modül belirtmiyoruz, projeyi doğrudan ana dizinde derliyoruz
      - name: Build AAR with NDK
        run: gradle assembleRelease --stacktrace

      # Yol klasörsüz ve isminden emin olmak için joker (*) karakterli
      - name: Upload AAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-TiffBitmapFactory-16KB
          path: build/outputs/aar/*-release.aar
